name: brjr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06934
title: Brotherjunior Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#6a6a6a'
    - '#b5b5b5'
    - '#2d2d2d'
    - '#f9f9f9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.3872624614741653
purpose: []
