name: brjr
favicon: null
layout_spectrum: 0.7681294286157936
typography_spectrum: 0.006288953823968768
title: Brotherjunior Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.08961201692000031
  lightness: 0.2554182589519769
  saturation: 0.2574512963183224
  rhythmicContrast: 0.3872624614741653
purpose: []
