title: Brotherjunior Photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#A7A7A7'
    - '#CDCDCD'
    - '#767676'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: brjr
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.09865092
layout_spectrum: 0.306914
